AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    get-enriched-photos

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Api:
        Cors:
            AllowMethods: "'GET,OPTIONS'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"
    Function:
        Timeout: 60
        MemorySize: 128

Resources:
    GetPhotosFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: src/
            Handler: app.lambdaHandler
            Runtime: nodejs20.x
            Architectures:
                - x86_64
            Events:
                Photos:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /photos
                        Method: get
                        RequestParameters:
                            - method.request.querystring.title
                            - method.request.querystring.albumTitle
                            - method.request.querystring.email
                            - method.request.querystring.limit
                            - method.request.querystring.offset
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - app.ts
    GetPhotoByIdFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: get-photo-by-id
            Handler: app.lambdaHandler
            Runtime: nodejs20.x
            Architectures:
                - x86_64
            Events:
                Photos:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /photos/{id}
                        Method: get
                        RequestParameters:
                            - method.request.path.id
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - app.ts                    

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    PhotosApi:
        Description: 'API Gateway endpoint URL for Prod stage for get photos function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/photos/'
    GetPhotosFunction:
        Description: 'Get photos Lambda Function ARN'
        Value: !GetAtt GetPhotosFunction.Arn
    GetPhotosFunctionIamRole:
        Description: 'Implicit IAM Role created for Get photos function'
        Value: !GetAtt GetPhotosFunctionRole.Arn
