---
name: Build and Deploy Lambda and Api Gateway
on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                    - info
                    - warning
                    - debug
    push:
        branches: [main]
        paths:
            - 'endpoints/get-enriched-photos/**'
jobs:
    deploy-lambda:
        name: Build and Deploy
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./endpoints/get-enriched-photos
        env:
            BUCKET: metaphoto-bucket
            DIST: dist
            REGION: us-east-1

        steps:
            - uses: aws-actions/setup-sam@v2
              with:
                  use-installer: true

            - name: Checkout
              uses: actions/checkout@v2

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.REGION }}

            # - uses: actions/setup-node@v2
            #   with:
            #     node-version: '14'

            - name: Install Dependencies
              run: |
                  node --version
                  npm install

            - name: SAM Build
              run: sam build

            - name: SAM Deploy
              run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name metaphoto-lambda-stack ---region ${{ env.REGION }}  --s3-bucket
